include: package:pedantic_mono/analysis_options.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore # [Using json_serializable v5 causes invalid_annotation_target warnings · Issue #488 · rrousselGit/freezed](https://github.com/rrousselGit/freezed/issues/488)
    todo: ignore
  exclude:
    - "lib/generated/**" # L10n ファイルは除外

linter:
  rules:
    avoid_positional_boolean_parameters: false
    require_trailing_commas: true
    lines_longer_than_80_chars: true
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    one_member_abstracts: false
    unawaited_futures: true
    prefer_constructors_over_static_methods: false
    flutter_style_todos: false
